@echo off
echo Loading environment variables...
call setup-env-variable.bat
echo Environment variables loaded.
echo Starting HSDS...
hsds --root_dir %ROOT_DIR% --host localhost --port 5101 --password_file admin/config/passwd.txt --logfile hs.log   --loglevel DEBUG  --config_dir=admin/config --count=4  